### ISSUE TITLE
Failed to activate the linter-spell-shellscript package

### ISSUE THREAD

**Issue by s-light** [dhabyx/linter-spell-shellscript#2]
steps to reproduce:
1. start Atom with an already opened .sh file

seems to be the same error as after the fresh install #1 

**Atom**: 1.21.0 x64
**Electron**: 1.6.9
**OS**: Ubuntu 17.04
**Thrown From**: [linter-spell-shellscript](https://github.com/dhabyx/linter-spell-shellscript) package 0.2.0

### Stack Trace

Failed to activate the linter-spell-shellscript package

```
At logger.setLevel is not a function

TypeError: logger.setLevel is not a function
    at /packages/linter-spell-shellscript/node_modules/natural/lib/natural/brill_pos_tagger/lib/Brill_POS_Tagger.js:26:8)
    at /packages/linter-spell-shellscript/node_modules/natural/lib/natural/brill_pos_tagger/lib/Brill_POS_Tagger.js:137:3)
    at Module.get_Module._compile (/usr/share/atom/resources/app/src/native-compile-cache.js:106:36)
    at Object.value [as .js] (/usr/share/atom/resources/app/src/compile-cache.js:239:29)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (/app.asar/static/index.js:47:45)
    at require (/usr/share/atom/resources/app/src/native-compile-cache.js:66:33)
    at /packages/linter-spell-shellscript/node_modules/natural/lib/natural/index.js:81:26)
    at /packages/linter-spell-shellscript/node_modules/natural/lib/natural/index.js:83:3)
    at Module.get_Module._compile (/usr/share/atom/resources/app/src/native-compile-cache.js:106:36)
    at Object.value [as .js] (/usr/share/atom/resources/app/src/compile-cache.js:239:29)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (/app.asar/static/index.js:47:45)
    at require (/usr/share/atom/resources/app/src/native-compile-cache.js:66:33)
    at /packages/linter-spell-shellscript/node_modules/linter-spell-word-list/main.js:3:14)
    at /packages/linter-spell-shellscript/node_modules/linter-spell-word-list/main.js:78:45)
    at Module.get_Module._compile (/usr/share/atom/resources/app/src/native-compile-cache.js:106:36)
    at Object.value [as .js] (/usr/share/atom/resources/app/src/compile-cache.js:239:29)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (/app.asar/static/index.js:47:45)
    at require (/usr/share/atom/resources/app/src/native-compile-cache.js:66:33)
    at Object.provideDictionary (/packages/linter-spell-shellscript/lib/main.js:35:20)
    at Package.module.exports.Package.activateServices (/usr/share/atom/resources/app/src/package.js:443:75)
    at Package.module.exports.Package.activateNow (/usr/share/atom/resources/app/src/package.js:256:22)
    at /usr/share/atom/resources/app/src/package.js:1030:34
    at Function.module.exports.Emitter.simpleDispatch (/usr/share/atom/resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (/usr/share/atom/resources/app/node_modules/event-kit/lib/emitter.js:141:34)
    at PackageManager.triggerDeferredActivationHooks (/usr/share/atom/resources/app/src/package-manager.js:712:40)
    at Promise.all.then (/usr/share/atom/resources/app/src/package-manager.js:649:18)
```

### Commands

```
```

### Non-Core Packages

```
busy-signal 1.4.3 
character-table 0.4.3 
copy-with-style 1.1.0 
fold-functions 0.5.0 
hey-pane 1.0.0 
highlight-selected 0.13.1 
intentions 1.1.5 
language-arduino 0.4.3 
language-latex 1.1.1 
language-pcb 1.0.1 
language-restructuredtext 1.1.0 
language-svg 0.9.2 
linter 2.2.0 
linter-eslint 8.2.1 
linter-gcc 0.7.1 
linter-jsonlint 1.3.0 
linter-markdown 5.2.0 
linter-pylama 0.9.4 
linter-shellcheck 1.4.6 
linter-spell 0.15.0 
linter-spell-html 0.7.0 
linter-spell-javascript 0.8.0 
linter-spell-project 0.2.0 
linter-spell-shellscript 0.2.0 
linter-stylelint 4.0.2 
linter-tidy 2.3.1 
linter-ui-default 1.6.8 
linter-xmllint 1.4.3 
markdown-pdf 2.1.0 
markdown-scroll-sync 2.1.2 
markdown-toc 0.4.2 
```

**Comment by dflock** [comment]
Any chance you could do another release, so that this bug gets fixed in the wild? apm is still installing 0.2.0, which has this problem.

**Comment by Redsandro** [comment]
Encountered this. Are there any other linters for `.sh` files?

**Comment by RubenKelevra** [comment]
Still happening
